- name: load containerd
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: apply sysctl
  become: true
  ansible.builtin.command: /usr/sbin/sysctl --system

- name: swapoff
  become: true
  ansible.builtin.command: swapoff -a

- name: restart containerd
  become: true
  ansible.builtin.systemd:
    name: containerd.service
    state: restarted
    daemon_reload: yes

- name: restart rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog.service
    state: restarted

- name: reboot
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 1200
